export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const UPDATE_CURRENT_SCREEN = 'UPDATE_CURRENT_SCREEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_NOTIFICATION_BADGE = 'UPDATE_NOTIFICATION_BADGE';
export const UPDATE_MESSAGE_BADGE = 'UPDATE_MESSAGE_BADGE';
export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN';


export const SET_ERROR = 'SET_ERROR';

export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const REGISTER_API_SUCCESS = 'REGISTER_API_SUCCESS';
export const DELETE_USER_API_SUCCESS = 'DELETE_USER_API_SUCCESS';
export const FORGET_PASSWORD_API_SUCCESS = 'FORGET_PASSWORD_API_SUCCESS';
export const SEND_OPT_API_SUCCESS = 'SEND_OPT_API_SUCCESS';
export const RESET_PASSWORD_API_SUCCESS = 'RESET_PASSWORD_API_SUCCESS';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const SUBMIT_OTP_API_SUCCESS = 'SUBMIT_OTP_API_SUCCESS';
export const RESEND_OTP_API_SUCCESS = 'RESEND_OTP_API_SUCCESS';
export const GET_PROFILE_API_SUCCESS = 'GET_PROFILE_API_SUCCESS';


export const EDIT_PROFILE_API_SUCCESS = 'EDIT_PROFILE_API_SUCCESS';
export const UPDATE_PROFILE_PIC_API_SUCCESS = 'UPDATE_PROFILE_PIC_API_SUCCESS';
export const UPDATE_PROFILE_PIC_API_ERROR = 'UPDATE_PROFILE_PIC_API_ERROR';
// export const GET_USER_PROFILE_API_SUCCESS = 'GET_USER_PROFILE_API_SUCCESS';
export const GET_OUR_STAFF_API_SUCCESS = 'GET_OUR_STAFF_API_SUCCESS';
export const GET_OUR_SPEAKER_API_SUCCESS = 'GET_OUR_SPEAKER_API_SUCCESS';

export const GET_SERMONS_API_SUCCESS = 'GET_SERMONS_API_SUCCESS';
export const GET_POSTS_API_SUCCESS = 'GET_POSTS_API_SUCCESS';
export const GET_EVENTS_API_SUCCESS = 'GET_EVENTS_API_SUCCESS';
export const GET_UPCOMING_EVENTS_API_SUCCESS = 'GET_UPCOMING_EVENTS_API_SUCCESS';
export const GET_REQUESTED_PRAYER_API_SUCCESS = 'GET_REQUESTED_PRAYER_API_SUCCESS';
export const GET_NOTIFICATIONS_API_SUCCESS = 'GET_NOTIFICATIONS_API_SUCCESS';
export const GET_ANNOUNCEMENT_API_SUCCESS = 'GET_ANNOUNCEMENT_API_SUCCESS';
export const GET_BOOKS_API_SUCCESS = 'GET_BOOKS_API_SUCCESS';

export const GET_SERMONS_DETAIL_API_SUCCESS = 'GET_SERMONS_DETAIL_API_SUCCESS';
export const GET_POST_DETAIL_API_SUCCESS = 'GET_POST_DETAIL_API_SUCCESS';
export const GET_ANNOUNCEMENT_DETAIL_API_SUCCESS = 'GET_ANNOUNCEMENT_DETAIL_API_SUCCESS';
export const GET_EVENT_DETAIL_API_SUCCESS = 'GET_EVENT_DETAIL_API_SUCCESS';
export const GET_UPCOMING_EVENT_DETAIL_API_SUCCESS = 'GET_UPCOMING_EVENT_DETAIL_API_SUCCESS';
export const GET_OUR_STAFF_DETAIL_API_SUCCESS = 'GET_OUR_STAFF_DETAIL_API_SUCCESS';
export const GET_OUR_SPEAKER_DETAIL_API_SUCCESS = 'GET_OUR_SPEAKER_DETAIL_API_SUCCESS';
export const GET_BOOKS_DETAIL_API_SUCCESS = 'GET_BOOKS_DETAIL_API_SUCCESS';

export const CONTACT_API_SUCCESS = 'CONTACT_API_SUCCESS';
export const REQUEST_PRAYER_API_SUCCESS = 'REQUEST_PRAYER_API_SUCCESS';
export const ABOUT_API_SUCCESS = 'ABOUT_API_SUCCESS';
export const HOME_BANNER_API_SUCCESS = 'HOME_BANNER_API_SUCCESS';

export const GET_GROUPS_API_SUCCESS = 'GET_GROUPS_API_SUCCESS';
export const GET_MESSAGES_API_SUCCESS = 'GET_MESSAGES_API_SUCCESS';
export const SEND_MESSAGES_API_SUCCESS = 'SEND_MESSAGES_API_SUCCESS';
export const DELETE_MESSAGES_API_SUCCESS = 'DELETE_MESSAGES_API_SUCCESS';